# Site settings
title: '唱响创之歌'  # Your Title
tagline: 'a green boy'  # A brief tagline for your site
timezone: 'Asia/Shanghai'
destination: ./_site

# Build settings
encoding: UTF-8
markdown: kramdown
#for publish
#highlighter: pygments
#for local
#highlighter: true
baseurl: # the subpath of your site, e.g. /blog/
codeurl: /code/
fragmenturl: /fragment/

# Personal info
avatar: header.jpg
email: yanchuang1994@gmail.com
github: https://github.com/LukeDemons
weibo: //weibo.com/yanchuang9412
music: //music.163.com/#/user/home?id=31071885
twitter: https://twitter.com/yanchuang9412

# Logo setting
logocolor: '#000'