markdown: kramdown
highlighter: pygments
permalink: blog/:year/:month/:day/:title.html
paginate: 6
paginate_path: page/:num

blog:
    name:              LukeDemons
    description:       a green boy
    title:             唱响创之歌
    url:               lukedemons.github.io
    duoshuo:           lukedemons
    tongji:            627ae7154a273bb9b736aeedc26308f3
    qiniu:             7xie8u.com1.z0.glb.clouddn.com
author:
    name:              LukeDemons
    email:             yanchuang1994@gmail.com
    weibo:             http://weibo.com/2609477805/
    github:            https://github.com/LukeDemons
    logo:              /res/img/header.jpg
    douban:
        name:          101952310
        key:           # 豆瓣API Key